package Proyecto;


import java.awt.Color;
import java.awt.Dimension;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author arlet
 */
public class Ventana_RetiroEfectivo extends javax.swing.JFrame {

    /**
     * Creates new form RetiroEfectivo
     */
    public Ventana_RetiroEfectivo() {
        initComponents();
        this.setSize(new Dimension(1275, 585));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNaranja = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        pnlClaro = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtMonto = new javax.swing.JTextField();
        lblSaldo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtDecripción = new javax.swing.JTextArea();
        btnRealizarRetiro = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        pnlNaranja.setBackground(new java.awt.Color(224, 122, 95));
        pnlNaranja.setPreferredSize(new java.awt.Dimension(1270, 66));
        pnlNaranja.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Administrador: Nombre_Usuario");
        pnlNaranja.add(jLabel9);
        jLabel9.setBounds(10, 23, 291, 22);

        btnCerrarSesion.setBackground(new java.awt.Color(224, 122, 95));
        btnCerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setMaximumSize(new java.awt.Dimension(160, 40));
        btnCerrarSesion.setMinimumSize(new java.awt.Dimension(160, 40));
        btnCerrarSesion.setPreferredSize(new java.awt.Dimension(160, 40));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        pnlNaranja.add(btnCerrarSesion);
        btnCerrarSesion.setBounds(1080, 15, 160, 40);

        getContentPane().add(pnlNaranja);
        pnlNaranja.setBounds(0, 0, 1270, 66);

        pnlClaro.setBackground(new java.awt.Color(244, 241, 222));
        pnlClaro.setMaximumSize(new java.awt.Dimension(1270, 583));
        pnlClaro.setMinimumSize(new java.awt.Dimension(1270, 583));
        pnlClaro.setPreferredSize(new java.awt.Dimension(1270, 583));
        pnlClaro.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Retiro de efectivo");
        pnlClaro.add(jLabel7);
        jLabel7.setBounds(0, 120, 1270, 58);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Descripción del retiro");
        pnlClaro.add(jLabel8);
        jLabel8.setBounds(390, 370, 170, 30);

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setText("Regresar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlClaro.add(btnCancelar);
        btnCancelar.setBounds(710, 450, 170, 70);

        txtMonto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMonto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtMonto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMontoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMontoFocusLost(evt);
            }
        });
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });
        pnlClaro.add(txtMonto);
        txtMonto.setBounds(560, 280, 320, 30);

        lblSaldo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaldo.setText("2080");
        pnlClaro.add(lblSaldo);
        lblSaldo.setBounds(560, 220, 320, 30);

        TxtDecripción.setColumns(20);
        TxtDecripción.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TxtDecripción.setForeground(new java.awt.Color(102, 102, 102));
        TxtDecripción.setRows(5);
        TxtDecripción.setText("Escribe aquí la descripción del retiro");
        TxtDecripción.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtDecripciónFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtDecripciónFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(TxtDecripción);

        pnlClaro.add(jScrollPane1);
        jScrollPane1.setBounds(560, 360, 320, 70);

        btnRealizarRetiro.setBackground(new java.awt.Color(204, 204, 204));
        btnRealizarRetiro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRealizarRetiro.setText("Realizar retiro");
        btnRealizarRetiro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btnRealizarRetiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRealizarRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarRetiroActionPerformed(evt);
            }
        });
        pnlClaro.add(btnRealizarRetiro);
        btnRealizarRetiro.setBounds(390, 450, 170, 70);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Monto a retirar      $");
        pnlClaro.add(jLabel13);
        jLabel13.setBounds(390, 280, 170, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Saldo total en caja $");
        pnlClaro.add(jLabel14);
        jLabel14.setBounds(390, 220, 170, 30);

        getContentPane().add(pnlClaro);
        pnlClaro.setBounds(0, 0, 1270, 583);
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_RetiroEfectivo().setVisible(true);
            }
        });
    }
    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       this.dispose();
        Interfaz_Principal IA = new Interfaz_Principal();
        IA.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRealizarRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarRetiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRealizarRetiroActionPerformed

    private void txtMontoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontoFocusGained
        if(txtMonto.getText().equals("$")){
            txtMonto.setText("");
            txtMonto.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtMontoFocusGained

    private void txtMontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontoFocusLost
        if(txtMonto.getText().equals("")){
            txtMonto.setText("$");
            txtMonto.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtMontoFocusLost

    private void TxtDecripciónFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtDecripciónFocusGained
        if(TxtDecripción.getText().equals("Escribe aquí la descripción del retiro")){
            TxtDecripción.setText("");
            TxtDecripción.setForeground(Color.black);
        }
    }//GEN-LAST:event_TxtDecripciónFocusGained

    private void TxtDecripciónFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtDecripciónFocusLost
        if(TxtDecripción.getText().equals("")){
            TxtDecripción.setText("Escribe aquí la descripción del retiro");
            TxtDecripción.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_TxtDecripciónFocusLost

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        this.dispose();
        Ventana_Acceso VA = new Ventana_Acceso();
        VA.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxtDecripción;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnRealizarRetiro;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JPanel pnlClaro;
    private javax.swing.JPanel pnlNaranja;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
