/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author diana
 */
public class Ventana_Cliente_Registrar extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Usuario_RegistrarUsuario
     */
    public Ventana_Cliente_Registrar() {
        initComponents();
        
    }
    
    
    //public String Tel_Cliente="",Nom_Cliente="",Ape_Cliente="",Direccion_Cliente="";
    
    public String Actual_Nombre_Usuario,Actual_Apellido_Usuario,Actual_Cargo,Actual_Telefono;
    public int pedido;
    String Direccion;
    private ConeccionBD CBD = new ConeccionBD();
    
    private boolean Vacio(){
        boolean vacio=true;
        if(!txtNombre.getText().equals("Nombre") && !txtApellido.getText().equals("Apellido.") && !txtTelefono.getText().equals("Teléfono.")
                 && validarDomicilio(txtCalle,txtNumero,txtColonia,txtEntre));

        return vacio;
    }
    
    private void MandaInfoVCP(){
        Ventana_Cliente_Principal VCP = new Ventana_Cliente_Principal();
        VCP.Actual_Nombre_Usuario = Actual_Nombre_Usuario;
        VCP.Actual_Apellido_Usuario = Actual_Apellido_Usuario;
        VCP.Actual_Cargo = Actual_Cargo;
        this.dispose();
        VCP.setVisible(true);
    }
    private void MandaInfoVPR(){
        Ventana_Pedido_Registrar VPR = new Ventana_Pedido_Registrar();
        VPR.Actual_Nombre_Usuario = Actual_Nombre_Usuario;
        VPR.Actual_Apellido_Usuario = Actual_Apellido_Usuario;
        VPR.Actual_Cargo = Actual_Cargo;
        VPR.Actual_Telefono= Actual_Telefono;
        if(!Vacio()){
        VPR.Reg_Telefono = txtTelefono.getText();
        VPR.Reg_Nombre = txtNombre.getText()+" "+txtApellido.getText();
        VPR.Reg_Direccion = Direccion;
        }
        this.dispose();
        VPR.setVisible(true);
    }
    
    private void Limpiar(){
        txtNombre.setText("Nombre.");
        txtNombre.setForeground(new Color(102,102,102));
        txtApellido.setText("Apellido.");
        txtApellido.setForeground(new Color(102,102,102));
        txtTelefono.setText("Teléfono.");
        txtTelefono.setForeground(new Color(102,102,102));
        txtCalle.setText("Calle.");
        txtCalle.setForeground(new Color(102,102,102));
        txtNumero.setText("Número.");
        txtNumero.setForeground(new Color(102,102,102));
        txtColonia.setText("Colonia.");
        txtColonia.setForeground(new Color(102,102,102));
        txtEntre.setText("Entre.");
        txtEntre.setForeground(new Color(102,102,102));
        
    }
    
    private void RegistrarCliente(){
         String nombre, apellido,telefono,direccion;
            nombre=txtNombre.getText();
            apellido=txtApellido.getText();
            telefono=txtTelefono.getText();
            direccion=Direccion;
            
            try {
                Connection conectar = CBD.conectar();
                String sql = "INSERT into cliente values(?,?,?,?)";
                
                PreparedStatement pst = conectar.prepareStatement(sql);
                pst.setString(1, telefono);
                pst.setString(2, nombre);
                pst.setString(3, apellido);
                pst.setString(4, direccion);
                
                pst.executeUpdate();
                conectar.close();
                JOptionPane.showMessageDialog(null, "Registro exitoso.");
               
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Error al registrar.");
         }
     }
    public boolean validarDomicilio(JTextField calle,JTextField numero,JTextField colonia,JTextField entre){
       if(calle.getText().length()<1){
           calle.requestFocus();
           return false;
       }
       if(numero.getText().length()<1){
           numero.requestFocus();
           return false;
       }
       if(colonia.getText().length()<1){
           colonia.requestFocus();
           return false;
       }
       return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCabezera = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        pnlFondo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlInformacion = new javax.swing.JPanel();
        txtTelefono = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCalle = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtColonia = new javax.swing.JTextField();
        txtEntre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1270, 583));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        pnlCabezera.setBackground(new java.awt.Color(224, 122, 95));
        pnlCabezera.setMaximumSize(new java.awt.Dimension(1270, 66));
        pnlCabezera.setMinimumSize(new java.awt.Dimension(1270, 66));
        pnlCabezera.setPreferredSize(new java.awt.Dimension(1270, 66));
        pnlCabezera.setLayout(null);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsuario.setText("Administrador: Nombre_Usuario");
        pnlCabezera.add(lblUsuario);
        lblUsuario.setBounds(10, 20, 790, 30);

        btnCerrarSesion.setBackground(new java.awt.Color(224, 122, 95));
        btnCerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setMaximumSize(new java.awt.Dimension(160, 40));
        btnCerrarSesion.setMinimumSize(new java.awt.Dimension(160, 40));
        btnCerrarSesion.setPreferredSize(new java.awt.Dimension(160, 40));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        pnlCabezera.add(btnCerrarSesion);
        btnCerrarSesion.setBounds(1080, 15, 160, 40);

        getContentPane().add(pnlCabezera);
        pnlCabezera.setBounds(0, 0, 1270, 70);

        pnlFondo.setBackground(new java.awt.Color(244, 241, 222));
        pnlFondo.setMaximumSize(new java.awt.Dimension(1270, 583));
        pnlFondo.setMinimumSize(new java.awt.Dimension(1270, 583));
        pnlFondo.setPreferredSize(new java.awt.Dimension(1270, 583));
        pnlFondo.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Registrar cliente");
        pnlFondo.add(jLabel7);
        jLabel7.setBounds(0, 70, 1270, 58);

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistrar.setText("Registrar cliente");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        pnlFondo.add(btnRegistrar);
        btnRegistrar.setBounds(440, 480, 170, 70);

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancelar.setText("Regresar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlFondo.add(btnCancelar);
        btnCancelar.setBounds(660, 480, 170, 70);

        pnlInformacion.setBackground(new java.awt.Color(244, 241, 222));
        pnlInformacion.setLayout(null);

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefono.setText("Teléfono.");
        txtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusLost(evt);
            }
        });
        pnlInformacion.add(txtTelefono);
        txtTelefono.setBounds(100, 10, 202, 26);

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setText("Nombre.");
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        pnlInformacion.add(txtNombre);
        txtNombre.setBounds(100, 60, 202, 26);

        txtApellido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(102, 102, 102));
        txtApellido.setText("Apellido.");
        txtApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidoFocusLost(evt);
            }
        });
        pnlInformacion.add(txtApellido);
        txtApellido.setBounds(100, 110, 202, 26);

        txtCalle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCalle.setForeground(new java.awt.Color(102, 102, 102));
        txtCalle.setText("Calle.");
        txtCalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCalleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCalleFocusLost(evt);
            }
        });
        pnlInformacion.add(txtCalle);
        txtCalle.setBounds(100, 160, 202, 26);

        txtNumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNumero.setForeground(new java.awt.Color(102, 102, 102));
        txtNumero.setText("Número.");
        txtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumeroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroFocusLost(evt);
            }
        });
        pnlInformacion.add(txtNumero);
        txtNumero.setBounds(100, 210, 202, 26);

        txtColonia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtColonia.setForeground(new java.awt.Color(102, 102, 102));
        txtColonia.setText("Colonia.");
        txtColonia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtColoniaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtColoniaFocusLost(evt);
            }
        });
        pnlInformacion.add(txtColonia);
        txtColonia.setBounds(100, 260, 202, 26);

        txtEntre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEntre.setForeground(new java.awt.Color(102, 102, 102));
        txtEntre.setText("Entre.");
        txtEntre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEntreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEntreFocusLost(evt);
            }
        });
        pnlInformacion.add(txtEntre);
        txtEntre.setBounds(100, 310, 202, 26);

        pnlFondo.add(pnlInformacion);
        pnlInformacion.setBounds(440, 130, 390, 340);

        getContentPane().add(pnlFondo);
        pnlFondo.setBounds(0, 0, 1270, 583);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        try {
            if(pedido==1) MandaInfoVPR();
            else MandaInfoVCP();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Direccion = txtCalle+" "+txtNumero+" "+txtColonia+" "+txtEntre;
        if (Vacio()==false) {
            int resp = JOptionPane.showConfirmDialog(null, 
                "¿Los datos son correctos?", "Registrar.",JOptionPane.OK_CANCEL_OPTION);
            if(resp == 0){
                RegistrarCliente();
                if(pedido!=1){
                int resp2 = JOptionPane.showConfirmDialog(null, 
                    "¿Desea hacer un nuevo registro?", "Registrar.",JOptionPane.YES_NO_OPTION);
                if(resp2 == 1)
                    MandaInfoVCP();
                else
                    Limpiar();
                }
                else{
                   MandaInfoVPR();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Se ha cancelado el registro.");
                Limpiar();
            }
            
        }
        else
            JOptionPane.showMessageDialog(null, "Hay campos vacios.");
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        this.dispose();
        Ventana_Acceso VA = new Ventana_Acceso();
        VA.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained
        if(txtNombre.getText().equals("Nombre.")){
            txtNombre.setText("");
            txtNombre.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNombreFocusGained

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        if(txtNombre.getText().equals("")){
            txtNombre.setText("Nombre.");
            txtNombre.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoFocusGained
        if(txtApellido.getText().equals("Apellido.")){
            txtApellido.setText("");
            txtApellido.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtApellidoFocusGained

    private void txtApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoFocusLost
        if(txtApellido.getText().equals("")){
            txtApellido.setText("Apellido.");
            txtApellido.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtApellidoFocusLost

    private void txtTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusGained
        if(txtTelefono.getText().equals("Teléfono.")){
            txtTelefono.setText("");
            txtTelefono.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtTelefonoFocusGained

    private void txtTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusLost
        if(txtTelefono.getText().equals("")){
            txtTelefono.setText("Teléfono.");
            txtTelefono.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtTelefonoFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            lblUsuario.setText(Actual_Cargo+": "+Actual_Nombre_Usuario+" "+Actual_Apellido_Usuario);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_formWindowOpened

    private void txtCalleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCalleFocusGained
        if(txtTelefono.getText().equals("Calle.")){
            txtTelefono.setText("");
            txtTelefono.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCalleFocusGained

    private void txtCalleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCalleFocusLost
        if(txtTelefono.getText().equals("")){
            txtTelefono.setText("Calle.");
            txtTelefono.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtCalleFocusLost

    private void txtNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroFocusGained
        if(txtTelefono.getText().equals("Número.")){
            txtTelefono.setText("");
            txtTelefono.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNumeroFocusGained

    private void txtNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroFocusLost
        if(txtTelefono.getText().equals("")){
            txtTelefono.setText("Número.");
            txtTelefono.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtNumeroFocusLost

    private void txtColoniaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColoniaFocusGained
        if(txtTelefono.getText().equals("Colonia.")){
            txtTelefono.setText("");
            txtTelefono.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtColoniaFocusGained

    private void txtColoniaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColoniaFocusLost
        if(txtTelefono.getText().equals("")){
            txtTelefono.setText("Colonia.");
            txtTelefono.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtColoniaFocusLost

    private void txtEntreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEntreFocusGained
        if(txtTelefono.getText().equals("Entre.")){
            txtTelefono.setText("");
            txtTelefono.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtEntreFocusGained

    private void txtEntreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEntreFocusLost
        if(txtTelefono.getText().equals("")){
            txtTelefono.setText("Entre.");
            txtTelefono.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtEntreFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Cliente_Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Cliente_Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Cliente_Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Cliente_Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Cliente_Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlCabezera;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlInformacion;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtEntre;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
