/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diana
 */
public class Ventana_Pedido_Registrar extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Usuario_RegistrarUsuario
     */
    public String Actual_Nombre_Usuario,Actual_Apellido_Usuario,Actual_Telefono,Actual_U,Actual_C,
            Actual_Correo,Actual_Direccion,Actual_Cargo,Actual_Fecha,Actual_Status,id_Usuario;

    private ConeccionBD CBD = new ConeccionBD();
    private DefaultTableModel m;
    
    public Ventana_Pedido_Registrar() {
        initComponents();
        m = (DefaultTableModel) tblDetalle.getModel();
        tblDetalle.setModel(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void obtenerIdUsuario(){
        String sql = "select ID_Usuario from usuarios where nombre='"+Actual_Nombre_Usuario+"' and Apellido = '"+Actual_Apellido_Usuario+"' and Telefono = '"+Actual_Telefono+"';";
        System.out.print(sql);
        try{
            Connection conectar = CBD.conectar();
            Statement st = conectar.createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.next();
            id_Usuario = rs.getString(1);
            conectar.close(); 
        }catch(Exception e){}
    }
    
    private void mandaInfoIPP(Ventana_Pedido_Principal vtn){
        vtn.Actual_Nombre_Usuario=Actual_Nombre_Usuario;
        vtn.Actual_Apellido_Usuario=Actual_Apellido_Usuario;
        vtn.Actual_Telefono=Actual_Telefono;
        vtn.Actual_U=Actual_U;
        vtn.Actual_C=Actual_C;
        vtn.Actual_Correo=Actual_Correo;
        vtn.Actual_Direccion=Actual_Direccion;
        vtn.Actual_Cargo=Actual_Cargo;
        vtn.Actual_Fecha=Actual_Fecha;
        vtn.Actual_Status=Actual_Status;
        this.dispose();
        vtn.setVisible(true);
    }
    
    private void mandaInfoIPP(Ventana_Cliente_Registrar vtn){
        vtn.Actual_Nombre_Usuario=Actual_Nombre_Usuario;
        vtn.Actual_Apellido_Usuario=Actual_Apellido_Usuario;
        vtn.Actual_Cargo=Actual_Cargo;
        this.dispose();
        vtn.setVisible(true);
    }
    
    private void consultarCliente(){
        String sql = "select Nom_Cliente,Ape_Cliente,Direccion_cliente from cliente where Tel_Cliente = '"+txtTelefono.getText()+"';";
        System.out.print(sql);
        try{
            Connection conectar = CBD.conectar();
            Statement st = conectar.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                txtNombre.setText(rs.getString(1)+" "+rs.getString(2));
                txtDireccion.setText(rs.getString(3));
            }else{
                btnRegistrarClientes.setEnabled(true);
                showMessageDialog(this,"Se necesita registrar el cliente");
                txtNombre.requestFocus();
                txtNombre.setEnabled(true);
                txtDireccion.setEnabled(true);
            }
            conectar.close(); 
        }catch(Exception e){}
    }
    
    private void cargarCombos(){
        String sql = "";
        try{
            sql="select ID_Productos,Nom_Producto,Tamaño,Precio from productos order by Nom_Producto;";
            Connection conectar = CBD.conectar();
            Statement st = conectar.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                cmbProductos.addItem(rs.getString(1)+", "+rs.getString(2)+", "+rs.getString(3)+", $"+rs.getString(4));
            }
            conectar.close(); 
        }catch(Exception e){}
    }
    
    private String obtenerIndiceMax(){
        String sql = "select  max(ID_Pedido) from pedido;";
        System.out.print(sql);
        String maximo="";
        try{
            Connection conectar = CBD.conectar();
            Statement st = conectar.createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.next();
            maximo = rs.getString(1);
            conectar.close(); 
        }catch(Exception e){}
        return maximo;
    }
    
    private void registrarPedidoYDetalle(){
        
        
        Calendar calendario = new GregorianCalendar();
        
        //showMessageDialog(this,date.ge);
        
        int hora =calendario.get(Calendar.HOUR_OF_DAY),minutos = calendario.get(Calendar.MINUTE),segundos = calendario.get(Calendar.SECOND);
        int anio = calendario.get(Calendar.YEAR),mes  = calendario.get(Calendar.MONTH)+1,dia = calendario.get(Calendar.DAY_OF_MONTH);
        
        String hCompleta = hora+":"+minutos+":"+segundos,fCompleta = anio+"/"+mes+"/"+dia;
        
        try {
                Connection conectar = CBD.conectar();
                String sql = "insert into pedido(Usuarios_ID_Usuario,Cliente_Tel_Cliente,Fecha,Hora,Total)"
                        + "values (?,?,?,?,?);";
                
                PreparedStatement pst = conectar.prepareStatement(sql);
                pst.setString(1, id_Usuario);
                pst.setString(2, txtTelefono.getText());
                pst.setString(3, fCompleta);
                pst.setString(4, hCompleta);
                pst.setString(5, lblTotal.getText());
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Registro exitoso.");
               CBD.desconectar();
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Error al registrar.");
         }
        String indiceMax = obtenerIndiceMax();
        for (int i = 0; i < m.getRowCount(); i++) {
            try {
                Connection conectar = CBD.conectar();//1            2                           3                           4                   5           6               7
                String sql = "insert into Detalle_Pedido(Pedido_ID_Pedido, Pedido_Usuarios_ID_Usuario, Pedido_Cliente_Tel_Cliente, Productos_ID_Productos, Cantidad, PrecioUnitario, Importe)"
                        + "values (?,?,?,?,?,?,?);";
                String c[] = new String[4];
                
                c=(tblDetalle.getValueAt(i,1)+"").split(",");
                
                //showMessageDialog(this,indiceMax+", "+id_Usuario+", "+txtTelefono.getText()+", "+c[0]+", "+tblDetalle.getValueAt(i,0)+", "+tblDetalle.getValueAt(i,2)+", "+tblDetalle.getValueAt(i,3));
                        
                PreparedStatement pst = conectar.prepareStatement(sql);
                pst.setString(1, indiceMax);
                pst.setString(2, id_Usuario);
                pst.setString(3, txtTelefono.getText());
                pst.setString(4, c[0]);
                pst.setString(5, tblDetalle.getValueAt(i,0)+"");
                pst.setString(6, tblDetalle.getValueAt(i,2)+"");
                pst.setString(7, tblDetalle.getValueAt(i,3)+"");
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Registro exitoso.");
               CBD.desconectar();
         } catch (SQLException e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
         }
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlCabezera = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        pnlInformacion = new javax.swing.JPanel();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cmbProductos = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        btnRegistrarClientes = new javax.swing.JButton();
        jsCantidad = new javax.swing.JSpinner();
        btnEliminar = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1270, 583));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        pnlFondo.setBackground(new java.awt.Color(244, 241, 222));
        pnlFondo.setMaximumSize(new java.awt.Dimension(1270, 583));
        pnlFondo.setMinimumSize(new java.awt.Dimension(1270, 583));
        pnlFondo.setPreferredSize(new java.awt.Dimension(1270, 583));
        pnlFondo.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Registrar Pedido");
        pnlFondo.add(jLabel7);
        jLabel7.setBounds(0, 110, 1270, 58);

        pnlCabezera.setBackground(new java.awt.Color(224, 122, 95));
        pnlCabezera.setMaximumSize(new java.awt.Dimension(1270, 66));
        pnlCabezera.setMinimumSize(new java.awt.Dimension(1270, 66));
        pnlCabezera.setPreferredSize(new java.awt.Dimension(1270, 66));
        pnlCabezera.setLayout(null);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsuario.setText("Administrador: Nombre_Usuario");
        pnlCabezera.add(lblUsuario);
        lblUsuario.setBounds(10, 20, 310, 30);

        btnCerrarSesion.setBackground(new java.awt.Color(224, 122, 95));
        btnCerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setMaximumSize(new java.awt.Dimension(160, 40));
        btnCerrarSesion.setMinimumSize(new java.awt.Dimension(160, 40));
        btnCerrarSesion.setPreferredSize(new java.awt.Dimension(160, 40));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        pnlCabezera.add(btnCerrarSesion);
        btnCerrarSesion.setBounds(1080, 15, 160, 40);

        pnlFondo.add(pnlCabezera);
        pnlCabezera.setBounds(0, 0, 1270, 70);

        pnlInformacion.setBackground(new java.awt.Color(244, 241, 222));
        pnlInformacion.setLayout(null);

        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDireccion.setText("Direccion *");
        txtDireccion.setEnabled(false);
        pnlInformacion.add(txtDireccion);
        txtDireccion.setBounds(310, 80, 200, 30);

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTelefono.setText("Telefono *");
        pnlInformacion.add(txtTelefono);
        txtTelefono.setBounds(50, 20, 180, 30);

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombre.setText("Nombre del cliente *");
        txtNombre.setEnabled(false);
        pnlInformacion.add(txtNombre);
        txtNombre.setBounds(50, 80, 200, 30);

        cmbProductos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Productos" }));
        cmbProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductosActionPerformed(evt);
            }
        });
        pnlInformacion.add(cmbProductos);
        cmbProductos.setBounds(70, 150, 340, 30);

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setText("Consultar");
        btnBuscar.setActionCommand("Registrar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        pnlInformacion.add(btnBuscar);
        btnBuscar.setBounds(260, 20, 130, 30);

        btnRegistrarClientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarClientes.setText("Registrar cliente");
        btnRegistrarClientes.setActionCommand("Registrar");
        btnRegistrarClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btnRegistrarClientes.setEnabled(false);
        btnRegistrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClientesActionPerformed(evt);
            }
        });
        pnlInformacion.add(btnRegistrarClientes);
        btnRegistrarClientes.setBounds(440, 20, 130, 30);

        jsCantidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pnlInformacion.add(jsCantidad);
        jsCantidad.setBounds(0, 150, 60, 30);

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setActionCommand("Registrar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        pnlInformacion.add(btnEliminar);
        btnEliminar.setBounds(440, 200, 130, 30);

        btnProductos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProductos.setText("Agregar");
        btnProductos.setActionCommand("Registrar");
        btnProductos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        pnlInformacion.add(btnProductos);
        btnProductos.setBounds(440, 150, 130, 30);

        pnlFondo.add(pnlInformacion);
        pnlInformacion.setBounds(90, 190, 590, 250);

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Producto", "Precio Unitario", "Importe"
            }
        ));
        jScrollPane1.setViewportView(tblDetalle);

        pnlFondo.add(jScrollPane1);
        jScrollPane1.setBounds(720, 190, 480, 230);

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pnlFondo.add(lblTotal);
        lblTotal.setBounds(790, 420, 300, 30);

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistrar.setText("Registrar pedido");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        pnlFondo.add(btnRegistrar);
        btnRegistrar.setBounds(370, 490, 170, 70);

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancelar.setText("Regresar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlFondo.add(btnCancelar);
        btnCancelar.setBounds(690, 490, 170, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Total: $");
        pnlFondo.add(jLabel2);
        jLabel2.setBounds(720, 420, 70, 30);

        getContentPane().add(pnlFondo);
        pnlFondo.setBounds(0, 0, 1270, 583);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProductosActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        this.dispose();
        Ventana_Acceso VA = new Ventana_Acceso();
        VA.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        registrarPedidoYDetalle();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Ventana_Pedido_Principal vtn = new Ventana_Pedido_Principal();
        mandaInfoIPP(vtn);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        consultarCliente();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        String cad[] = new String[4];
        cad = (cmbProductos.getSelectedItem().toString()).split(",");
        //try{
            Object O[] = new Object[4];
            int cant = Integer.parseInt(jsCantidad.getValue()+"");
            float precio = Float.parseFloat(cad[3].substring(2));
            float total = precio*cant;
            O[0] = cant;
            O[1] = cad[0]+", "+cad[1]+", "+cad[2];
            O[2] = precio;
            O[3] = total;
            if(m.getRowCount()>0) lblTotal.setText((Float.parseFloat(lblTotal.getText())+total)+"");
            else lblTotal.setText(total+"");
            m.addRow(O);
        //}catch(Exception e){}
        
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnRegistrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClientesActionPerformed
        Ventana_Cliente_Registrar vtn = new Ventana_Cliente_Registrar();
        mandaInfoIPP(vtn);
    }//GEN-LAST:event_btnRegistrarClientesActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblUsuario.setText(Actual_Cargo+": "+Actual_Nombre_Usuario+" "+Actual_Apellido_Usuario);
        cargarCombos();
        obtenerIdUsuario();
        
    }//GEN-LAST:event_formWindowOpened

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int renglon = tblDetalle.getSelectedRow();
        if(renglon==-1){
            showMessageDialog(this,"Necesita seleccionar un renglon de la tabla para eleminar");
        }else{
            float resta = Float.parseFloat(tblDetalle.getValueAt(renglon,3)+"");
            if(m.getRowCount()>0) lblTotal.setText((Float.parseFloat(lblTotal.getText())-resta)+"");
            else lblTotal.setText(0+"");            
            m.removeRow(renglon);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Pedido_Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Pedido_Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Pedido_Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Pedido_Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Pedido_Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarClientes;
    private javax.swing.JComboBox<String> cmbProductos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jsCantidad;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlCabezera;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlInformacion;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
