/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diana
 */
public class Ventana_Usuario_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Usuario_Principal
     */
    public Ventana_Usuario_Principal() {
        initComponents();
    }
    
    public String Nombre_Usuario,Apellido_Usuario,Telefono,U,C,Correo,Direccion,Cargo,Fecha,Status;
    public String Nombre_U,Apellido_U,TelU,Usu,Cont,CorreoU,DireccionU,CargoU,FechaU,StatusU;
    
    private ConeccionBD CBD = new ConeccionBD();
    Connection conectar = CBD.conectar();
    private Ventana_Usuario_ModificarUsuario VUM = new Ventana_Usuario_ModificarUsuario();
    
    private void CargarUsuarios(){
        DefaultTableModel mod = new DefaultTableModel();
        
        mod.addColumn("Nombre");
        mod.addColumn("Apellido");
        mod.addColumn("TELEFONO");
        mod.addColumn("Nom_Usuario");
        mod.addColumn("Contraseña");
        mod.addColumn("Correo");
        mod.addColumn("Direccion");
        mod.addColumn("Cargo");
        mod.addColumn("Fecha_Registro");
        mod.addColumn("Status");
        
        tblUsuarios.setModel(mod);
        String sql=""; 
        sql = "select Nombre,Apellido,TELEFONO,Nom_Usuario,Contraseña,Correo,Direccion,Cargo,Fecha_Registro,Status from usuarios";
        String[] Datos = new String[10];
        try {
            Statement st = conectar.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()){
                Datos[0]=rs.getString(1);
                Datos[1]=rs.getString(2);
                Datos[2]=rs.getString(3);
                Datos[3]=rs.getString(4);
                Datos[4]=rs.getString(5);
                Datos[5]=rs.getString(6);
                Datos[6]=rs.getString(7);
                Datos[7]=rs.getString(8);
                Datos[8]=rs.getString(9);
                Datos[9]=rs.getString(10);
                
                mod.addRow(Datos);
            }
            
        } catch (Exception e) {
        }
        
            
        
    }
    
    public void UsuarioSeleccionado(int Fila){
        Nombre_U = tblUsuarios.getValueAt(Fila, 0).toString();
        Apellido_U= tblUsuarios.getValueAt(Fila, 1).toString();
        TelU= tblUsuarios.getValueAt(Fila, 2).toString();
        Usu= tblUsuarios.getValueAt(Fila, 3).toString();
        Cont= tblUsuarios.getValueAt(Fila, 4).toString();
        CorreoU= tblUsuarios.getValueAt(Fila, 5).toString();
        DireccionU= tblUsuarios.getValueAt(Fila, 6).toString();
        CargoU= tblUsuarios.getValueAt(Fila, 7).toString();
        FechaU= tblUsuarios.getValueAt(Fila, 8).toString();
        StatusU= tblUsuarios.getValueAt(Fila, 9).toString();
    }
    private void MandaInfoVUM(){
        VUM.Nombre_Usuario=Nombre_U;
        VUM.Apellido_Usuario=Apellido_U;
        VUM.Telefono=TelU;
        VUM.U=Usu;
        VUM.C=Cont;
        VUM.Correo=CorreoU;
        VUM.Direccion=DireccionU;
        VUM.Cargo=CargoU;
        VUM.Fecha=FechaU;
        VUM.Status=StatusU;
        
        VUM.Nombre_Usuario_Actual=Nombre_Usuario;
        VUM.Apellido_Usuario_Actual=Apellido_Usuario;
        VUM.Cargo_Actual=Cargo;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminarUsuario = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlCabezera = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        btnCerrarSesion2 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnRegres = new javax.swing.JButton();
        btnModificarUsuario = new javax.swing.JButton();
        btnRegistrarUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1270, 583));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        btnEliminarUsuario.setBackground(new java.awt.Color(244, 241, 222));
        btnEliminarUsuario.setMaximumSize(new java.awt.Dimension(1270, 583));
        btnEliminarUsuario.setMinimumSize(new java.awt.Dimension(1270, 583));
        btnEliminarUsuario.setPreferredSize(new java.awt.Dimension(1270, 583));
        btnEliminarUsuario.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Usuarios");
        btnEliminarUsuario.add(lblTitulo);
        lblTitulo.setBounds(0, 120, 1270, 58);

        pnlCabezera.setBackground(new java.awt.Color(224, 122, 95));
        pnlCabezera.setMaximumSize(new java.awt.Dimension(1270, 66));
        pnlCabezera.setMinimumSize(new java.awt.Dimension(1270, 66));
        pnlCabezera.setPreferredSize(new java.awt.Dimension(1270, 66));
        pnlCabezera.setLayout(null);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsuario.setText("Administrador: Nombre_Usuario");
        pnlCabezera.add(lblUsuario);
        lblUsuario.setBounds(10, 20, 650, 30);

        btnCerrarSesion2.setBackground(new java.awt.Color(224, 122, 95));
        btnCerrarSesion2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCerrarSesion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        btnCerrarSesion2.setText("Cerrar sesión");
        btnCerrarSesion2.setBorder(null);
        btnCerrarSesion2.setBorderPainted(false);
        btnCerrarSesion2.setMaximumSize(new java.awt.Dimension(160, 40));
        btnCerrarSesion2.setMinimumSize(new java.awt.Dimension(160, 40));
        btnCerrarSesion2.setPreferredSize(new java.awt.Dimension(160, 40));
        btnCerrarSesion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesion2ActionPerformed(evt);
            }
        });
        pnlCabezera.add(btnCerrarSesion2);
        btnCerrarSesion2.setBounds(1080, 15, 160, 40);

        btnEliminarUsuario.add(pnlCabezera);
        pnlCabezera.setBounds(0, 0, 1270, 60);

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setActionCommand("Registrar");
        btnRegresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        btnEliminarUsuario.add(btnRegresar);
        btnRegresar.setBounds(850, 470, 170, 70);

        btnRegres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegres.setText("Eliminar usuario");
        btnRegres.setActionCommand("Registrar");
        btnRegres.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btnRegres.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresActionPerformed(evt);
            }
        });
        btnEliminarUsuario.add(btnRegres);
        btnRegres.setBounds(660, 470, 170, 70);

        btnModificarUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificarUsuario.setText("Modificar usuario");
        btnModificarUsuario.setActionCommand("Registrar");
        btnModificarUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btnModificarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUsuarioActionPerformed(evt);
            }
        });
        btnEliminarUsuario.add(btnModificarUsuario);
        btnModificarUsuario.setBounds(460, 470, 170, 70);

        btnRegistrarUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarUsuario.setText("Registrar usuario");
        btnRegistrarUsuario.setActionCommand("Registrar");
        btnRegistrarUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btnRegistrarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuarioActionPerformed(evt);
            }
        });
        btnEliminarUsuario.add(btnRegistrarUsuario);
        btnRegistrarUsuario.setBounds(260, 470, 170, 70);

        tblUsuarios.setBackground(new java.awt.Color(244, 241, 222));
        tblUsuarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblUsuarios.getTableHeader().setReorderingAllowed(false);
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        btnEliminarUsuario.add(jScrollPane1);
        jScrollPane1.setBounds(260, 200, 760, 250);

        getContentPane().add(btnEliminarUsuario);
        btnEliminarUsuario.setBounds(0, 0, 1270, 590);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuarioActionPerformed
        this.dispose();
        Ventana_Usuario_RegistrarUsuario VURU = new Ventana_Usuario_RegistrarUsuario();
        VURU.setVisible(true);
    }//GEN-LAST:event_btnRegistrarUsuarioActionPerformed

    private void btnModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUsuarioActionPerformed
        this.dispose();
        Ventana_Usuario_ModificarUsuario VUMU = new Ventana_Usuario_ModificarUsuario();
        VUMU.setVisible(true);
    }//GEN-LAST:event_btnModificarUsuarioActionPerformed

    private void btnRegresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresActionPerformed
        this.dispose();
        Ventana_Usuario_EliminarUsuario VUEU = new Ventana_Usuario_EliminarUsuario();
        VUEU.setVisible(true);
    }//GEN-LAST:event_btnRegresActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
        Interfaz_Principal IA = new Interfaz_Principal();
        IA.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCerrarSesion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesion2ActionPerformed
        this.dispose();
        Ventana_Acceso VA = new Ventana_Acceso();
        VA.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesion2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            CargarUsuarios();
            lblUsuario.setText(Cargo+": "+Nombre_Usuario+" "+Apellido_Usuario);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_formWindowOpened

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        try {
            int Fila = tblUsuarios.getSelectedRow();
            UsuarioSeleccionado(Fila);
        } catch (Exception e) {
        }
        
        
        
    }//GEN-LAST:event_tblUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Usuario_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Usuario_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Usuario_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Usuario_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Usuario_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion2;
    private javax.swing.JPanel btnEliminarUsuario;
    private javax.swing.JButton btnModificarUsuario;
    private javax.swing.JButton btnRegistrarUsuario;
    private javax.swing.JButton btnRegres;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlCabezera;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
