/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arlet
 */
public class Ventana_Producto_Eliminar extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Usuario_Principal
     */
    public Ventana_Producto_Eliminar() {
        initComponents();
    }

    public String Nom_Producto="",Tipo="",Tamaño="",Descripcion="";
    
    public float Precio=0;
    
    public String Actual_Nombre_Usuario,Actual_Apellido_Usuario,Actual_Cargo;
    
    private ConeccionBD CBD = new ConeccionBD();
    Connection conectar = CBD.conectar();
    
    private void MandaInfoVPP(){
        Ventana_Producto_Principal VPP = new Ventana_Producto_Principal();
        VPP.Actual_Nombre_Usuario=Actual_Nombre_Usuario;
        VPP.Actual_Apellido_Usuario=Actual_Apellido_Usuario;
        VPP.Actual_Cargo=Actual_Cargo;
        this.dispose();
        VPP.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelClaro = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlCabezera = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnConsultaNombre = new javax.swing.JButton();
        btnEliminarPedido = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1270, 583));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        panelClaro.setBackground(new java.awt.Color(244, 241, 222));
        panelClaro.setMaximumSize(new java.awt.Dimension(1270, 583));
        panelClaro.setMinimumSize(new java.awt.Dimension(1270, 583));
        panelClaro.setPreferredSize(new java.awt.Dimension(1270, 583));
        panelClaro.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Eliminar producto");
        panelClaro.add(lblTitulo);
        lblTitulo.setBounds(0, 120, 1270, 58);

        pnlCabezera.setBackground(new java.awt.Color(224, 122, 95));
        pnlCabezera.setMaximumSize(new java.awt.Dimension(1270, 66));
        pnlCabezera.setMinimumSize(new java.awt.Dimension(1270, 66));
        pnlCabezera.setPreferredSize(new java.awt.Dimension(1270, 66));
        pnlCabezera.setLayout(null);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsuario.setText("Administrador: Nombre_Usuario");
        pnlCabezera.add(lblUsuario);
        lblUsuario.setBounds(10, 20, 500, 30);

        btnCerrarSesion.setBackground(new java.awt.Color(224, 122, 95));
        btnCerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setMaximumSize(new java.awt.Dimension(160, 40));
        btnCerrarSesion.setMinimumSize(new java.awt.Dimension(160, 40));
        btnCerrarSesion.setPreferredSize(new java.awt.Dimension(160, 40));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        pnlCabezera.add(btnCerrarSesion);
        btnCerrarSesion.setBounds(1080, 15, 160, 40);

        panelClaro.add(pnlCabezera);
        pnlCabezera.setBounds(0, 0, 1270, 60);

        btnConsultaNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultaNombre.setText("Consultar");
        btnConsultaNombre.setActionCommand("Registrar");
        btnConsultaNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, new java.awt.Color(0, 0, 0), java.awt.Color.black, java.awt.Color.black));
        btnConsultaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaNombreActionPerformed(evt);
            }
        });
        panelClaro.add(btnConsultaNombre);
        btnConsultaNombre.setBounds(800, 270, 130, 30);

        btnEliminarPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminarPedido.setText("Eliminar Producto");
        btnEliminarPedido.setActionCommand("Registrar");
        btnEliminarPedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btnEliminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPedidoActionPerformed(evt);
            }
        });
        panelClaro.add(btnEliminarPedido);
        btnEliminarPedido.setBounds(370, 480, 170, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre del producto");
        panelClaro.add(jLabel1);
        jLabel1.setBounds(340, 270, 200, 30);

        txtNombreProducto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombreProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreProducto.setText("NombreProducto");
        txtNombreProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreProductoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreProductoFocusLost(evt);
            }
        });
        panelClaro.add(txtNombreProducto);
        txtNombreProducto.setBounds(560, 270, 200, 30);

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setActionCommand("Registrar");
        btnRegresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        panelClaro.add(btnRegresar);
        btnRegresar.setBounds(760, 480, 170, 60);

        tblProductos.setBackground(new java.awt.Color(244, 241, 222));
        tblProductos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idProducto", "NombreProducto", "Tipo", "Tamaño", "Precio", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblProductos.getTableHeader().setReorderingAllowed(false);
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(0).setResizable(false);
            tblProductos.getColumnModel().getColumn(1).setResizable(false);
            tblProductos.getColumnModel().getColumn(2).setResizable(false);
            tblProductos.getColumnModel().getColumn(3).setResizable(false);
            tblProductos.getColumnModel().getColumn(4).setResizable(false);
            tblProductos.getColumnModel().getColumn(5).setResizable(false);
        }

        panelClaro.add(jScrollPane1);
        jScrollPane1.setBounds(370, 320, 560, 140);

        getContentPane().add(panelClaro);
        panelClaro.setBounds(0, 0, 1270, 590);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Funcion para eliminar un pedido
     */
    private void EliminarProducto(){
        int id, fila;
        fila = tblProductos.getSelectedRow();
                
        id= Integer.parseInt(tblProductos.getValueAt(fila, 0).toString());
        try {
                Connection conectar = CBD.conectar();
                String sql = "delete from productos where ID_Productos = ?";
                
                PreparedStatement pst = conectar.prepareStatement(sql);
                pst.setInt(1, id);
                
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Eliminación exitosa.");
               
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Error al eliminar.");
         }
    }
    private void btnEliminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPedidoActionPerformed
        try {
            int resp = JOptionPane.showConfirmDialog(null, 
                "¿Desea eliminar?", "Eliminar",JOptionPane.OK_CANCEL_OPTION);
            if(resp==0){
                EliminarProducto();
                    limpiarTabla();
                    cargarProductos();
                    txtNombreProducto.setText("NombreProducto");
                    txtNombreProducto.setForeground(new Color(102,102,102));                
            }
                else{
                JOptionPane.showMessageDialog(null, "Se ha cancelado la eliminación");
                txtNombreProducto.setText("NombreProducto");
                txtNombreProducto.setForeground(new Color(102,102,102));
            }
         } catch (Exception e) {
        }
    }//GEN-LAST:event_btnEliminarPedidoActionPerformed

    private void btnConsultaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaNombreActionPerformed
         try {
            if (txtNombreProducto.getText().equals("NombreProducto")) {
                cargarProductos();
            }
            else
                ConsultaProductos();
            txtNombreProducto.setText("NombreProducto");
            txtNombreProducto.setForeground(new Color(102,102,102));
        } catch (Exception e) {
          }
    }//GEN-LAST:event_btnConsultaNombreActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        MandaInfoVPP();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtNombreProductoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreProductoFocusLost
       if(txtNombreProducto.getText().equals("")){
            txtNombreProducto.setText("NombreProducto");
            txtNombreProducto.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtNombreProductoFocusLost

    private void txtNombreProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreProductoFocusGained
        if(txtNombreProducto.getText().equals("NombreProducto")){
            txtNombreProducto.setText("");
            txtNombreProducto.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNombreProductoFocusGained

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        this.dispose();
        Ventana_Acceso VA = new Ventana_Acceso();
        VA.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblUsuario.setText(Actual_Cargo+": "+Actual_Nombre_Usuario+" "+Actual_Apellido_Usuario);
    }//GEN-LAST:event_formWindowOpened

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        try {
            int Fila = tblProductos.getSelectedRow();
            ProductoSeleccionado(Fila);
            CargaProducto();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar los datos e la tabla.(clic)");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tblProductosMouseClicked

    /**
     * Funcion para limpiar la tabla
     */
    public void limpiarTabla(){
        try {
            //System.out.println("Limpiando tabla");
            DefaultTableModel mod=(DefaultTableModel) tblProductos.getModel();
            int a=tblProductos.getRowCount()-1;
            for (int i = a; i >= 0; i--) {
                mod.removeRow(mod.getRowCount()-1);
            }
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }
    
    /**
     * Funcion para cargar los productos a la tabla
     */
    private void cargarProductos(){
        limpiarTabla();
        DefaultTableModel mod=(DefaultTableModel) tblProductos.getModel(); 
        tblProductos.setModel(mod);
        
        String sql=""; 
        sql = "select * from productos";
        String[] Datos = new String[6];
        try {
            Connection conectar = CBD.conectar();
            Statement st = conectar.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()){
                Datos[0]=rs.getString(1);
                Datos[1]=rs.getString(2);
                Datos[2]=rs.getString(3);
                Datos[3]=rs.getString(4);
                Datos[4]=rs.getString(5);
                Datos[5]=rs.getString(6); 
                
                mod.addRow(Datos);
            }
        conectar.close();    
        } catch (Exception e) {
        }
    
    }
    
    /**
     * Funcion para consultar productos en la base de datos
     */
    private void ConsultaProductos(){
        limpiarTabla();
        String nombre = txtNombreProducto.getText()+"%";
        String sql="select * from productos where Nom_Producto like '"+nombre+"'";
        
        String[] Datos = new String[6];
        DefaultTableModel mod=(DefaultTableModel) tblProductos.getModel();
        try {
            Connection conectar = CBD.conectar();
            Statement st = conectar.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()){
                Datos[0]=rs.getString(1);
                Datos[1]=rs.getString(2);
                Datos[2]=rs.getString(3);
                Datos[3]=rs.getString(4);
                Datos[4]=rs.getString(5);
                Datos[5]=rs.getString(6);
                
                mod.addRow(Datos);
            }
           // Limpiar();
        conectar.close();    
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar los datos de la tabla.(ConsultaProductos)");
        }
    }
    
    /**
     * Funcion para limpiar los campos
     */
    private void Limpiar(){
        txtNombreProducto.setText("NombreProducto");
        txtNombreProducto.setForeground(new Color(102,102,102));
    }
    
    /**
     * Funcion para guardar el producto seleccionado
     * @param Fila 
     */
    public void ProductoSeleccionado(int Fila){ 
        Nom_Producto = tblProductos.getValueAt(Fila, 1).toString();
    }
     
    /**
     * Funcion para cargar el nombre del producto en el campo
     */
    private void CargaProducto(){
        txtNombreProducto.setText(Nom_Producto);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Producto_Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Producto_Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Producto_Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Producto_Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Producto_Eliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConsultaNombre;
    private javax.swing.JButton btnEliminarPedido;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelClaro;
    private javax.swing.JPanel pnlCabezera;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtNombreProducto;
    // End of variables declaration//GEN-END:variables
}
